# Eigenvalues and Eigenvectors

In [1]:
#import the packages here
import matplotlib.pyplot as plt
from scipy import integrate
import numpy as np
%matplotlib notebook
%matplotlib inline


$$\vec{A} = 
\begin{pmatrix}
 11 &  -1 & 0\\
-1 &  12 & -1\\
 0 &  -1 & 11
\end{pmatrix}
$$

Find the eigenvalues and eigenvectors for the equation:

$$(\vec{A} - \lambda\vec{I})\vec{v} = 0,$$
where $\vec{v}$ are the eigenvectors and $\lambda$ is the eigenvalues

In [4]:
#define matrix
a = np.array([[11,-1,0],[-1,12,-1],[0,-1,11]])
a
#oh the transpose At = A

array([[11, -1,  0],
       [-1, 12, -1],
       [ 0, -1, 11]])

In [9]:
#find eigenvaules and eigenvectors
eigenvalues,eigenvectors = np.linalg.eig(a)
print('Eigenvalues: {}'.format(eigenvalues))
print('Eigenvectors:')
print('{}'.format(eigenvectors))


Eigenvalues: [13. 11. 10.]
Eigenvectors:
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01 -1.42827551e-15  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
