In [68]:
#import the packages here
import matplotlib.pyplot as plt
from scipy import integrate
import numpy as np
%matplotlib notebook
%matplotlib inline

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [69]:
a = np.array([[2,4,-7],[3,-3,0],[1,7,5]])
b = np.array(([[2,4],[3,-3],[1,7]]))
c = np.array([[-1,1],[1,-1]])
d = np.array([[-2,0],[-3,6]])

1. Multiply $\bf{A}$ by 2.5 

In [70]:
a2 = a * 2.5
a2

array([[  5. ,  10. , -17.5],
       [  7.5,  -7.5,   0. ],
       [  2.5,  17.5,  12.5]])

2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [74]:
#ca = np.dot(c, a)
#does not work, rows and columns do not match
ab = np.dot(a,b)
#does work, rows match columns
print(ab)
ba = np.dot(b,a)
#however, the other way around rows do not match columns.

[[  9 -53]
 [ -3  21]
 [ 28  18]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [75]:
cd = np.dot(c, d)
print(cd)
dc = np.dot(d, c)
dc
#if this is indeed dot product and not multiplication, then yes they will be different answers

[[-1  6]
 [ 1 -6]]


array([[ 2, -2],
       [ 9, -9]])

4. Find the transpose of $\bf{B}$

In [77]:
print(b)
bt = np.transpose(b)
print(bt)
#now you can dot bt to a since they allign
print(np.dot(bt,a))

[[ 2  4]
 [ 3 -3]
 [ 1  7]]
[[ 2  3  1]
 [ 4 -3  7]]
[[14  6 -9]
 [ 6 74  7]]


5. Add $\bf{C} + \bf{D}$

In [79]:

caddd = np.add(c,d)
caddd

array([[-3,  1],
       [-2,  5]])

6. Compute the determinate of $\bf{C}$

In [80]:
#manually
print(c)
detcm = (c[0][0] * c[1][1]) - (c[1][0]*c[0][1])
print(detcm)
#numpy
detcn = np.linalg.det(c)
print(detcn)

[[-1  1]
 [ 1 -1]]
0
0.0


7. Compute the determinate of $\bf{A}$

In [81]:
#using numpy
deta = np.linalg.det(a)
print(deta)

-257.9999999999998
