# Numpy (Numeric Python)
- A linear algebra library for python
- Numpy is the basis of many python libraries 
- Built on C library, so it is a fast library

## Numpy library is extensive, a few methods and functions
- Numpy arrays: creation methods
- Numpy arrays: manipulation methods
- Mathematical operations on Numpy arrays
- Matrix and vector operations
- Sorting methods
- Searching methods
- Statistical methods

In [ ]:
import numpy as np

# Numpy Arrays Creation Methods

### We can cast a python list into a 1D numpy array

In [5]:
#array
my_list = [0,1,2]
print(type(my_list))
arr = np.array(my_list)
print(type(arr))
arr

<class 'list'>
<class 'numpy.ndarray'>


array([0, 1, 2])

A mulitdimensonal numpy array can be mad from a python list of lists

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_mat))
my_mat

<class 'list'>


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
arr_multi = np.array(my_mat)
print(type(arr_multi))
arr_multi

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Double** brackets indicate it is a 2D array. **Single** brackets indicate 1D array.
Can also modify data type:

In [9]:
arr_multi = np.array(my_mat,dtype = np.float32)
arr_multi

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

Copying a numpy array

In [8]:
#start here
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_new = arr
arr_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr_new[0:3]= -1
arr_new

array([-1, -1, -1,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr

array([-1, -1, -1,  4,  5,  6,  7,  8,  9, 10])

By default numpy works with references to the arrays, this saves memory with large arrays. So if you can assing the array a new name and any modifications to it also apply to the original array. To make a second independent one, use the **copy** method.

In [14]:
arr_new = arr.copy()
arr_new

array([-1, -1, -1,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr_new[0:3] = 0
print('arr_new: ', arr_new)
print('arr: ', arr)

arr_new:  [ 0  0  0  4  5  6  7  8  9 10]
arr:  [-1 -1 -1  4  5  6  7  8  9 10]


### Create 0's and 1's

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3)) #(row,col)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
3*np.ones(3)

array([3., 3., 3.])

### Identity matrices:

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Equally spaced arrays
Create equally spaced array with a fixed step size using **arange**
>arange(start, stop, step_size)

By default start = 0, step_size = 1, and stop value is not included in the final array



array from 0 to 10 with step size of 1

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array from 5 to 11 with step size 1

In [22]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

array from 2 to 20 with step size = 2

In [23]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Equally spaced array with specific size
another useful method is **linspace**, which creates a specified number of equally spaced points
> linspace(start,stop,npoints)

In [24]:
np.linspace(0,5,10) 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Random Numbers

Numpy has many methods for generating random numbers. The methods are accessable from numpy.random

- rand: uniform distribution from 0 to 1
- randn: normal distribution centered at zero
- randint: random integer from [start,stop) *stop value not include*
- many more

In [27]:
np.random.rand(5)

array([0.32694791, 0.98866464, 0.53972358, 0.544751  , 0.91081647])

In [28]:
np.random.rand(5,5)

array([[0.62332642, 0.91113279, 0.76439642, 0.71259589, 0.97292293],
       [0.01654709, 0.68678583, 0.53712882, 0.86921067, 0.68486881],
       [0.67387113, 0.36548413, 0.56284628, 0.41213673, 0.52771578],
       [0.47456189, 0.53112249, 0.72504603, 0.46486389, 0.31450039],
       [0.99355398, 0.87520897, 0.10749547, 0.69943212, 0.56207116]])

In [29]:
np.random.randn(5)

array([-0.35065055,  1.23582559,  0.33591266,  0.33101394, -0.63117332])

In [30]:
np.random.randn(5,5)

array([[ 0.68575246, -0.32466246, -0.17989256, -0.71215201, -1.67479611],
       [-0.25821654,  0.10579802,  2.13163695, -1.90197458, -0.51201906],
       [ 0.21620368, -1.03135243,  1.26609696,  1.82302129,  2.02651195],
       [ 0.37839433, -1.00343899, -1.87055262,  1.22759099,  0.14872696],
       [-1.10319381, -0.78958424, -2.32209786,  1.73117144,  0.82216548]])

In [35]:
np.random.randint(1,100,3) #100 not included

array([24, 83, 59])

# Numpy Array Manipulation Methods
### Shape

Determine the shape of a numpy array using
> np.shape()

In [36]:
a = np.ones( (2,3) )
print(a)
print('shape of a (row, col): ',np.shape(a))


[[1. 1. 1.]
 [1. 1. 1.]]
shape of a (row, col):  (2, 3)


### Reshape

We can reshape our arrays, i.e. change the number of rows and columns. We just need to keep the product of rows and columns equal to the original array size.

In [37]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr.reshape(4,5) 

You can transpose an array via

In [40]:
arr.reshape(4,3).transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### Concatenate Multiple numpy arrays

In [ ]:
## Concatenate Row-wise
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

In [ ]:
## Concatenate Column-wise
np.concatenate((a, b.transpose()), axis=1)

In [ ]:
## Concatenate to generate a flat NumPy Array

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

### Flatten numpy array
- use **flatten( )** to collapse an np.array into a single dimension

In [ ]:
a = np.array([[1,2], [3,4]])
print(a)

In [ ]:
a.flatten()

### Determine unique elements of numpy array
- Use **np.unique( )**

In [ ]:
a = np.array([[1, 2], [2, 3]])
np.unique(a)

In [ ]:
#Unique rows
a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
print(a)

np.unique(a, axis=0)

In [ ]:
#unique columns
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
print(a)

np.unique(a, axis=1)

### Numpy array to Python lists
- Use **tolist( )**

In [44]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
print(type(a))

aa = a.tolist()
print(type(aa))

<class 'numpy.ndarray'>
<class 'list'>


# Numpy Operations

Many mathematical functions (see here: https://numpy.org/doc/1.23/reference/routines.math.html)

### Trig. Functions 

In [ ]:
a = np.array([1,2,3])
print("Trigonometric Sine   :", np.sin(a))
print("Trigonometric Cosine :", np.cos(a))
print("Trigonometric Tangent:", np.tan(a))

### Rounding arrays

Each element of an array can be rounded:
- up using np.ceil( )
- down using np.floor( )
- to the nearest integer using np.rint( )
- to a specific decimal place using np.round_( )

In [ ]:
a = np.linspace(1, 2, 7)
print(a)
print(np.ceil(a))
print(np.floor(a))
print(np.rint(a))
print(np.round_(a,2)) #round to 2 decimal places

### Exponents and Logs
- $log$ and $ln$ are one of those definitons that has no set standard. In numpy 
> np.log()

is the natrual log, $ln$

- Calculate element-by-element wise natural log with **np.log( )**
- Calculate element-by-element wise exponential with **np.exp( )**

In [ ]:
a = np.arange(1,6)
print(a)

print(np.log(a).round(2))
print(np.exp(a).round(2))

### Sum of array elements
Calculate array element sums using **np.sum( )**

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

print('sum along columns: ',a.sum(axis=0))
print('sum along rows: ',a.sum(axis=1))
print('sum along columns and rows: ', a.sum())

### Product of array elements
Calculate array element sums using **np.prod( )**

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

print('sum along columns: ',a.prod(axis=0))
print('sum along rows: ',a.prod(axis=1))
print('sum along columns and rows: ', a.prod())

### Square Root of array elements
Calculate array element sums using **np.sqrt( )**

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

print('square root of a: ', np.sqrt(a))

# Matrix and Vector Operations

### Dot Product (Scalar Product)
- np.dot( )

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
print(a)
print(b)
np.dot(a, b)

### Cross Product
- np.cross( )

In [ ]:
print(a)
print(b)
print(np.cross(a,b))
print(np.cross(b,a))

### Matrix Multiplication
- np.matmul( )

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
print(a)
print(b)
np.matmul(a, b)

### Vector Normalization
- np.linalg.norm( )

In [ ]:
a = np.arange(-4, 5)
print(a)
print(np.linalg.norm(a)) ## L2 Norm sum(|x|^2)^1/2

print(np.linalg.norm(a, 1)) ## L1 Norm, sum(|x|^1)^1/1


# Sorting Methods

### Sort a Numpy array
- Use ndarray.sort( ) method

In [ ]:
a = np.array([[1,4],[3,1]])

print('a: ',a)

print('1: ',np.sort(a)) ## sort based on rows

print('2: ',np.sort(a, axis=None)) ## sort the flattened array

print('3: ',np.sort(a, axis=0)) ## sort based on columns

print('4: ',np.sort(a, axis=1)) ## sort based on rows


### Order of indicies in sorted Numpy array
- Return the order of indicies that would sort the array using **np.argsort( )**

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)

In [ ]:
np.random.seed(10) #any int
np.random.randint(0,10,10)

# Searching Methods

### Indicies corresponding to maximum values
- np.argmax( ), returns the first indice of the maximum value in the array along a particular axis

In [ ]:
a = np.random.randint(1, 20, 10).reshape(2,5)
print(a)

print(np.argmax(a)) ## index in a flattend array


print(np.argmax(a, axis=0)) ## indices along columns

print(np.argmax(a, axis=1)) ## indices along rows

### Find indicies corresponding to minimum values
- similar to argmax, use **np.argmin( )**

In [ ]:
a = np.random.randint(1, 20, 10).reshape(2,5)
print(a)

print(np.argmin(a)) ## index in a flattend array


print(np.argmin(a, axis=0)) ## indices along columns

print(np.argmin(a, axis=1)) ## indices along rows

### Search based on condition
- **np.where( )** can be used to select between two arrays based on a condition

In [43]:
a = np.random.randint(-10, 10, 10)
print(a)

b = np.where(a < 0, 0, a)
print(b)

#if element < 0:
#    return 0
#else:
#    return element


[  4  -6   9  -5  -5   6 -10 -10   7  -7]
[4 0 9 0 0 6 0 0 7 0]


### More Conditionals

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
bool_arr = arr > 5
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr

In [ ]:
arr[arr>5]

## Statistical Methods
- Mean
- Median
- Standard Deviation

### Mean

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)
np.mean(a)

In [ ]:
np.mean(a, axis = 1) ## along the row axis

In [ ]:
np.mean(a, axis = 0) ## along the column axis

### Median

In [ ]:
np.median(a)

In [ ]:
np.median(a,axis = 1) ## along the row axis

In [ ]:
np.median(a, axis = 0) ## along the column axis

### Standard Deviation

In [ ]:
np.std(a)

In [ ]:
np.std(a,axis = 1) # along the row axis

In [ ]:
np.std(a, axis = 0)# along the column axis